FROM python:3.9 AS base
WORKDIR /code

FROM base AS dependencies
COPY ./back-fastapi/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


FROM dependencies AS development
COPY ./back-fastapi /code/
CMD ["uvicorn", "main:app", "--host", "back", "--reload"]
EXPOSE $BACK_PORT
