version: "3"
services:
  front:
    build:
      target: development
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./front-nuxt:/usr/src/app
      - /usr/src/app/node_modules

  back:
    build:
      target: development
    ports:
      - "${BACK_PORT}:3005"
    volumes:
      - ./back-express:/usr/src/app
      - /usr/src/app/node_modules

  db:
    volumes:
      - ./db-mysql/dev:/var/lib/mysql
