version: "3"
services:
  front:
    build:
      target: development
    # ports:
    # # any reason for the ports?
    #   - "24678:24678"
    volumes:
      - ./front-nuxt:/usr/src/app
      - /usr/src/app/node_modules

  back:
    build:
      target: development
    volumes:
      - ./back-express:/usr/src/app
      - /usr/src/app/node_modules

  db:
    volumes:
      - ./db-mysql/dev:/var/lib/mysql
