FROM node:20-slim AS base
WORKDIR /usr/src/app

FROM base AS dependencies
COPY ./front-nuxt/package*.json ./
# RUN npm i --prod=false
RUN npm i

FROM dependencies AS development
CMD [ "npm", "run", "dev" ]
EXPOSE 3000

FROM dependencies AS build
COPY ./front-nuxt .
COPY ./env .
RUN npm run build

FROM base AS production
COPY ./front-nuxt/package.json ./
ENV NODE_ENV=production
COPY --from=build /usr/src/app .
RUN npm prune --prod
CMD [ "node", ".output/server/index.mjs" ]
