services:
  front:
    build:
      target: development
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./front-nuxt:/usr/src/app
      - front_node_modules:/usr/src/app/node_modules

  back:
    build:
      target: development
    ports:
      - "${BACK_PORT}:8000"
    volumes:
      - ./back-fastapi:/code/
    # volumes:
    #   - ./back-express:/usr/src/app
    #   - back_node_modules:/usr/src/app/node_modules

  # db:
  #   volumes:
  #     - ./db-mysql/dev:/var/lib/mysql

volumes:
  front_node_modules:
  back_node_modules:
