version: "3.8"
services:
  server:
    container_name: "server-nginx"
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "80:80"
    depends_on:
      - front
      - back
    volumes:
      - ./server-nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server-nginx/logs:/var/log/nginx
    networks:
      - server_network
    restart: always

  front:
    container_name: "front-nuxt"
    build:
      context: .
      dockerfile: Dockerfile.front
    env_file:
      - ./.env
    networks:
      - server_network

  back:
    container_name: "back-express"
    build:
      context: .
      dockerfile: Dockerfile.back
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - server_network
      - data_network
    restart: unless-stopped

  db:
    container_name: "db-mysql"
    image: mysql:latest
    environment:
      - TZ=Europe/Paris
    env_file:
      - ./.env
    networks:
      - data_network

networks:
  server_network:
  data_network:
