version: "3"
services:
  front:
    build:
      target: development
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules: