version: "3"
services:
  back:
    build:
      target: development
    ports:
      - "${BACK_PORT}:3005"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  db:
    volumes:
      - ../db-mysql/dev:/var/lib/mysql

volumes:
  node_modules: